# Generated by Django 4.2.6 on 2023-10-13 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinasDiurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('componente', models.CharField(max_length=255, null=True)),
                ('carga_horaria', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(128)])),
                ('natureza', models.CharField(max_length=50, null=True)),
                ('semestre', models.PositiveIntegerField(null=True)),
                ('id_matriz', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinasNoturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('componente', models.CharField(max_length=255, null=True)),
                ('carga_horaria', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(128)])),
                ('natureza', models.CharField(max_length=50, null=True)),
                ('semestre', models.PositiveIntegerField(null=True)),
                ('id_matriz', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
