# Generated by Django 4.2.6 on 2023-10-13 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_digiescolhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinasdiurno',
            name='carga_horaria',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(192)]),
        ),
        migrations.AlterField(
            model_name='disciplinasnoturno',
            name='carga_horaria',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(192)]),
        ),
    ]
